### ISSUE TITLE
Have oui-field error-messages handle custom errors

### ISSUE THREAD

**Issue by FredericEspiau** [ovh-ux/ovh-ui-angular#148]
Here is my controller code :
````
onPasswordConfirmationChange () {
    this.newAccountForm.passwordConfirmation.$setValidity("isNotIdenticalToPassword", this.newAccount.password === this.newAccount.passwordConfirmation);
        }
````

and my `oui-field` :
````
<oui-field
    data-size="m"
    data-error-messages="{ isNotIdenticalToPassword: 'error message' }">
````

It doesn't work as `error-messages` only check a few standard errors.

I switched `isNotIdenticalToPassword` to `pattern` so it works but maybe we could have it accept all kind of errors.

**Comment by tremblaymath** [comment]
We only support these validations for the MVP(minimal viable product)
            required: "Mandatory.",
            number: "Invalid number.",
            email: "Invalid email.",
            min: "Too low ( min).",
            max: "Too high ( max).",
            minlength: "Too short ( characters min).",
            maxlength: "Too high ( characters max).",
            pattern: "Invalid format."
Effectively, it could be a  nice improvement. Help and time are welcome!
Do you want to contribute?

**Comment by tremblaymath** [comment]
We need to support https://github.com/angular-ui/ui-validate

**Comment by JDownloader** [comment]
@FredericEspiau I've made something that might help you, I also found that this will be useful. It include documentation with a password matching verification. Maybe we could talk about it later today.
https://github.com/ovh-ux/ovh-ui-angular/tree/feature/field-custom-validation

**Comment by Jisay** [comment]
@JDownloader: looking into your branch code.
https://github.com/ovh-ux/ovh-ui-angular/blob/161d2cc12fcfb9be010647efb6a333f78e8b267e/packages/oui-field/src/field.html#L26-L43

It should be great if `ngMessage` directives were repeated through a `ngRepeat` on `form.$error` keys. Like this we will be abble to declare more than one custom validator.

**Comment by AxelPeter** [comment]
Will be resolved by the net release :)

**Comment by FredericEspiau** [comment]
`Next`
