### ISSUE TITLE
oui-stepper : disable oui-step-form edit button

### ISSUE THREAD

**Issue by Jisay** [ovh-ux/ovh-ui-angular#201]
There is some cases that the edit button of a `oui-step-form` should be disabled.
For example when `oui-stepper.onFinish` callback is called and wait for a promise to be resolved.
I tried to disabling all the `oui-step-form` but it hides their contents and I don't think it's a good solution from a UX point of view.
I propose to create a new attribute on the `oui-stepper` component called `disable-edition` or something like this? If true all the `Modify this step` buttons become disabled.

**Comment by AxelPeter** [comment]
Yes, it could be a possibility for this case. I'll see with CX what they think about that.

**Comment by AxelPeter** [comment]
Not needed anymore
