### ISSUE TITLE
oui-datagrid - Dynamic columns with custom cell templates

### ISSUE THREAD

**Issue by Jisay** [ovh-ux/ovh-ui-angular#206]
It's currently not possible to use the `columns` attribute of a `oui-datagrid` when we want cells with custom template.
It's also impossible to use `ngIf` on a `oui-column` component.

Example:
```html
<oui-datagrid data-rows-loader="ctrl.myLoader($config)">
    <oui-column data-ng-if="ctrl.isValid"
                data-title="'My Title'">
        <span>My custom cell because I want to bind my property as a readable date</span>
    </oui-column>
</oui-datagrid>
```

**Comment by AxelPeter** [comment]
Sorry for the late answer.

> It's currently not possible to use the columns attribute of a oui-datagrid when we want cells with custom template.

This behaviour is normal. It's to avoid mixing properties from `columns` and `<oui-column>`. It doesn't seems natural.
Maybe we could go with a new property `template`, which could be compiled. For example:

```html
<oui-datagrid rows="$ctrl.data" page-size="5" columns="[{
  title: 'First name',
  property: 'firstName',
  template: '<span>Lorem ipsum {{$value}} dolor sit amet</span>',
  sortable: 'asc',
  searchable: true,
  filterable: true
}">
```

What do you think ?

For the second point, it comes from the way the datagrid is build with `DatagridColumnBuilder`. 
This needs an improvement.

**Comment by Jisay** [comment]
Thanks for the answer!
I found very strange to declare html into a controller. Html should be declared into the view, so into the html file.
For me the `ngIf` should work as expected on a `oui-column` and we avoid complexity into controller.
