### ISSUE TITLE
Bad remove on oui-chips

### ISSUE THREAD

**Issue by Mama59** [ovh-ux/ovh-ui-angular#278]
### Description

delete oui-chip with X button delete the bad element

### Steps to reproduce

Juste remove one element

**Expected behavior**:

Remove one chip

**Actual behavior**:

Remove the last chip

**Frequency**:
All the time

**Comment by AxelPeter** [comment]
Thanks for your feedback.

This bug will be fixed with this PR (https://github.com/ovh-ux/ovh-ui-angular/pull/279) and will be available with version 2.21.1 :)
