### ISSUE TITLE
oui-datagrid: pagination not working ok when totalCount more than 8 million

### ISSUE THREAD

**Issue by rmajasol** [ovh-ux/ovh-ui-angular#354]
### Description

Pagination element not working ok inside oui-datagrid when totalCount value equals to millions. 

### Steps to reproduce

1. Declaring oui-datagrid component in code with `page-size=20`: 
```html
<oui-datagrid id="myDatagrid" show-spinner="true" page-size="20" rows-loader="$ctrl.loadList($config)">
```
2. `$ctrl.loadList` returns a promise response with totalCount > 8 million:
```
{
  data: [...20 items list],
  meta: {
    totalCount: 8546132
  }
}
```

**Expected behavior**:

We expect pagination working ok

**Actual behavior**:

Pagination not working ok
![pagination_issue](https://user-images.githubusercontent.com/822842/52065989-f1d33f00-2577-11e9-80dd-74a08ade3643.png)

**Frequency**:

It happens when totalCount is more than about 1 million and `page-size` attribute value is lower enough to reproduce that error (e.g. 8million totalItems and page-size equals 20) 

### Additional information

Browser throws `RangeError: Maximum call stack size exceeded` at https://github.com/ovh-ux/ovh-ui-angular/blob/master/packages/oui-pagination/src/pagination.controller.js#L90

**Comment by AxelPeter** [comment]
Hi,
The component seems to not appreciate creating a dropdown with more than 400000 items.
The browser must think it's in a loop. Maybe we should showing an `input` when we have over 100 pages.

**Comment by AxelPeter** [comment]
This bug is now fixed with this release https://github.com/ovh-ux/ovh-ui-angular/releases/tag/v2.24.2
