### ISSUE TITLE
Missing dependency to @uirouter/angularjs

### ISSUE THREAD

**Issue by cbourgois** [ovh-ux/ovh-ui-angular#399]
### Description

Some packages use `ui-sref*` directives (see https://github.com/ovh-ux/ovh-ui-angular/search?q=ui-sref&unscoped_q=ui-sref) but there is no dependency to `@uirouter/angularjs`.

**Expected behavior**:

`@uirouter/angularjs` should be a peer dependency.

**Comment by AxelPeter** [comment]
Thanks for your feedback,
I've created a PR to fix that here: https://github.com/ovh-ux/ovh-ui-kit/pull/449

**Comment by AxelPeter** [comment]
This has been fixed with https://github.com/ovh-ux/ovh-ui-kit/releases/tag/v3.2.1
