### ISSUE TITLE
oui-header-tabs conflicts with active attribute and ui-sref-active

### ISSUE THREAD

**Issue by cbourgois** [ovh-ux/ovh-ui-angular#400]
### Description

There is some conflicts in `oui-header-tabs` if we want to set `active: false` for a `oui-header-tabs-item` but the `state` of this item is active (the css class `oui-header-tabs__item_active` is also applied by `ui-sref-active` directive).

See : https://github.com/ovh-ux/ovh-ui-angular/blob/master/packages/oui-header-tabs/src/header-tabs-item.html#L2-L3

**Comment by AxelPeter** [comment]
This behaviour seems normal to me. The `active` attribute is there only for the case you don't want to use the `state` attribute.

Why would you set manually the `active` state, if it's already covered by using the `state` attribute ?
Have you a use case ?

**Comment by cbourgois** [comment]
Related to the ui-router documentation (https://ui-router.github.io/ng1/docs/latest/modules/directives.html#uisrefactivedirective) : 

> The ui-sref-active directive applies the CSS class when the ui-sref/ui-state's target state **or any child state is active**. This is a "fuzzy match" which uses StateService.includes.

So if I have two tabs in my header-tabs : 

* "All todos", state: `app.todos`
* "Add a todo", state : `app.todos.new`

And the current state is `app.todos.new`,

Result : the both tabs are active.
Expected : only `app.todos.new` should be active.

**Comment by antleblanc** [comment]
@cbourgois I'm not able to transfer this issue to the new repository [ovh/ovh-ui-kit](https://github.com/ovh/ovh-ui-kit).

If you still encounter the issue, could you please open an Issue directly on the new repository?
Thank you!
